---
- hosts: cp-mgmt-server
  tasks:
  - name: "login"
    check_point_mgmt:
      command: login
      parameters:
        username: "{{mgmt_user}}"
        password: "{{mgmt_password}}"
        management: "{{mgmt_server}}"
      fingerprint: "{{fingerprint}}"
    register: login_response
  - name: "upload new subnet on gateway"
    check_point_mgmt:
      command: put-file
      parameters:
        file-name: "changeeth3.clish"
        file-content: "set interface eth3 ipv4-address 192.168.74.150 mask-length 24"
        file-path: "/home/admin/"
        targets: "R80.10-GW-1"
      session-data: "{{login_response}}"
  - name: "upload new interface state on gateway"
    check_point_mgmt:
      command: put-file
      parameters:
        file-name: "eth3-stateon.clish"
        file-content: "set interface eth3 state on"
        file-path: "/home/admin/"
        targets: "R80.10-GW-1"
      session-data: "{{login_response}}"
  - name: "upload turn off route on gateway"
    check_point_mgmt:
      command: put-file
      parameters:
        file-name: "routeoff.clish"
        file-content: "set static-route default nexthop gateway address 192.168.26.2 off"
        file-path: "/home/admin/"
        targets: "R80.10-GW-1"
      session-data: "{{login_response}}"
  - name: "upload new route on gateway"
    check_point_mgmt:
      command: put-file
      parameters:
        file-name: "routeon.clish"
        file-content: "set static-route default nexthop gateway address 192.168.74.160 on"
        file-path: "/home/admin/"
        targets: "R80.10-GW-1"
      session-data: "{{login_response}}"
  - name: "upload close old interface on gateway"
    check_point_mgmt:
      command: put-file
      parameters:
        file-name: "close-eth2.clish"
        file-content: "set interface eth2 state off"
        file-path: "/home/admin/"
        targets: "R80.10-GW-1"
      session-data: "{{login_response}}"
  - name: "upload save setup on gateway"
    check_point_mgmt:
      command: put-file
      parameters:
        file-name: "saveit.clish"
        file-content: "save config"
        file-path: "/home/admin/"
        targets: "R80.10-GW-1"
      session-data: "{{login_response}}"
  - name: "run all scripts"
    check_point_mgmt:
      command: run-script
      parameters:
        script-name: "runme.clish"
        script: "/bin/clish -f /home/admin/changeeth3.clish; /bin/clish -f /home/admin/eth3-stateon.clish; /bin/clish -f /home/admin/routeoff.clish; /bin/clish -f /home/admin/routeon.clish; /bin/clish -f /home/admin/close-eth2.clish; /bin/clish -f /home/admin/saveit.clish"
        targets: "R80.10-GW-1"
      session-data: "{{login_response}}"
  - name: "logout"
    check_point_mgmt:
      command: logout
      session-data: "{{login_response}}"
