---
- hosts: cp-mgmt-server
  tasks:
  - name: "login"
    check_point_mgmt:
      command: login
      parameters:
        username: "{{mgmt_user}}"
        password: "{{mgmt_password}}"
        management: "{{mgmt_server}}"
      fingerprint: "{{fingerprint}}"
    register: login_response
  - name: "run change routes script"
    check_point_mgmt:
      command: run-script
      parameters:
        script: "{{ROUTE_SCRIPT}}"
        script-name: "change-routes.sh"
        targets: "R80.10-GW-1"
      session-data: "{{login_response}}" 
  - name: "logout"
    check_point_mgmt:
      command: logout
      session-data: "{{login_response}}"
